name: CI with GitHub Actions using Ant and JUnit | © 2024 by LamGiaThinh

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check-out repository
        uses: actions/checkout@v3

      - name: Set up JDK 17 
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build project with Ant
        run: ant -noinput -buildfile CI/build.xml
      
      - name: List files after build
        run: ls -R  # Check for the output of the build step

      - name: Distribute jar-war file
        run: |
          echo "Checking for .jar files in the /CI/dist directory:"
          ls -R CI/dist  # List the contents of the dist directory
          mkdir -p staging
          cp CI/dist/*.jar staging/  # Update this path based on the actual output directory

      - name: Make hyperlink to jar-war file
        uses: actions/upload-artifact@v3
        with:
          name: 1.0-SNAPSHOT.jar
          path: staging
