name: CI with GitHub Actions using Ant and JUnit | © 2024 by LamGiaThinh

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check-out repository
        uses: actions/checkout@v3

      - name: Set up JDK 17 
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: List files in workspace
        run: ls -R

      - name: Build project with Ant
        run: ant -noinput -buildfile CI/build.xml # Adjusted to relative path
      
      - name: Distribute jar-war file
        run: mkdir staging && cp dist/*.jar staging
      
      - name: Make hyperlink to jar-war file
        uses: actions/upload-artifact@v3
        with:
          name: 1.0-SNAPSHOT.jar
          path: staging
